services:
  django:
    build: Containers/Django
    image: transcendence-django
    container_name: Django
    env_file: .env
    restart: on-failure
    volumes:
      - Django:/transcendence
      - staticfiles:/app/staticfiles # Volume pour les fichiers statiques
    networks:
      - Transcendence
    depends_on:
      - postgreSQL
  postgreSQL:
    build: Containers/PostgreSQL
    image: transcendence-postgresql
    container_name: PostgreSQL
    env_file: .env
    restart: unless-stopped
    volumes :
      - PostgreSQL:/var/lib/postgresql/15/main
    expose:
      - "5432"
    networks:
      - Transcendence
  nginx:
    build: Containers/Nginx
    image: transcendence-nginx
    container_name: Nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - staticfiles:/app/staticfiles  # Volume pour les fichiers statiques
    networks:
      - Transcendence
    depends_on:
      - django


volumes:
  Django:
    driver: local
    name: data_Django
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './transcendence_srcs'
  PostgreSQL:
    driver: local
    name: data_PostgreSQL
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './database'
  staticfiles:
    driver: local  # Volume pour partager les fichiers statiques entre Django et Ngin

networks:
  Transcendence:
    driver: bridge
    name: Transcendence