services:
  django:
    build: Containers/Django
    image: transcendence-django
    container_name: Django
    env_file: .env
    restart: on-failure
    volumes:
      - Django:/transcendence
      - staticfiles:/app/staticfiles # Volume pour les fichiers statiques
    networks:
      - Transcendence
    depends_on:
      - postgreSQL
      - redis
  postgreSQL:
    build: Containers/PostgreSQL
    image: transcendence-postgresql
    container_name: PostgreSQL
    env_file: .env
    restart: unless-stopped
    volumes :
      - PostgreSQL:/var/lib/postgresql/15/main
    expose:
      - "5432"
    networks:
      - Transcendence
  nginx:
    build: Containers/Nginx
    image: transcendence-nginx
    container_name: Nginx
    ports:
      - "443:443"
      - "80:80"  # Optionnel si tu veux rediriger HTTP vers HTTPS
      - "8000:8000"
    volumes:
      - staticfiles:/app/staticfiles  # Volume pour les fichiers statiques
      - mediafiles:/app/mediafiles
    networks:
      - Transcendence
    depends_on:
      - django
  redis:
    image: redis:alpine # Utilisation de l'image officielle Redis Alpine (légère)
    ports:
      - "6379:6379"


volumes:
  Django:
    driver: local
    name: data_Django
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './transcendence_srcs'
  PostgreSQL:
    driver: local
    name: data_PostgreSQL
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './database'
  staticfiles:
    driver: local  # Volume pour partager les fichiers statiques entre Django et Nginx
  mediafiles:
    driver: local
    name: mediafiles
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './transcendence_srcs/media'


networks:
  Transcendence:
    driver: bridge
    name: Transcendence