FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    nginx \
    openssl \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/nginx/ssl
RUN openssl req -x509 -nodes -out /etc/nginx/ssl/transcendence.crt -keyout /etc/nginx/ssl/transcendence.key -subj "/C=FR/ST=O/L=Perpignan/O=42/OU=42/CN=localhost/UID=gpeyre"

COPY ./default.conf /etc/nginx/conf.d/default.conf

EXPOSE 443
RUN rm /etc/nginx/sites-enabled/default

CMD ["nginx", "-g", "daemon off;"]